displayName=Alch Assistant
author=oletvck
description=Tracks the profit of items bought on the Grand Exchange and high alched, including the cost of nature runes.
tags=alch,alchemy,high,grand,exchange,ge,profit,money,nature,rune
plugins=com.oletvck.gealchprofit.GeAlchProfitPlugin
version=1.0
build=standard
